### ISSUE TITLE
Import error 

### ISSUE THREAD

**Issue by Duvuki** [bolozna/Multilayer-networks-library#6]
Hi @bolozna ,

Please could you help me out with below mentioned error:
ImportError: cannot import name 'sampling' from partially initialized module 'pymnet' (most likely due to a circular import) (/home/duvuki/anaconda3/envs/colstrike/lib/python3.9/site-packages/pymnet/__init__.py)

I searched for posts with solutions, and tried commenting from . import sampling  (last line)  in     _init_.py
Still receiving same error. 
Thanks in advance!!

**Comment by bokae** [comment]
I have the same issue.
